name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mylesim-keepr"
          heroku_email: "myles.sanigar@gmail.com"
          usedocker: true
          stack: "container"
          docker_build_args: |
            NODE_ENV
            MONGO_DB_PASSWORD
            SNOWPACK_PUBLIC_FIREBASE_API_KEY
        env:
          NODE_ENV: production
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          SNOWPACK_PUBLIC_FIREBASE_API_KEY: ${{ secrets.SNOWPACK_PUBLIC_FIREBASE_API_KEY }}
